# Site settings
title: Apache Flink Training
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/flink-training" # the subpath of your site, e.g. /blog/
url: "http://dataartisans.github.io" # the base hostname & protocol for your site

scala_version: "2.10"

# Build settings
markdown: kramdown
