# Site settings
title: Apache Flink&reg; Training
description: > # this means to ignore newlines until "baseurl:"
  Training material for Apache Flink™, including environment setup
  implementation of programs using the Flink APIs, and packaging,
  execution and monitoring of Flink programs.
baseurl: ""
images: "/hs-fs/hubfs/Training/images"
css: "/hs-fs/hubfs/Training/css"
js: "/hs-fs/hubfs/Training/js"
docs: https://ci.apache.org/projects/flink/flink-docs-release-1.7
ff: https://www.ververica.com/flink-forward/resources

tests: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/test/java/com/dataartisans/flinktraining/exercises/datastream_java
javasolutions: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/java/com/dataartisans/flinktraining/solutions/datastream_java
scalasolutions: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/scala/com/dataartisans/flinktraining/solutions/datastream_scala
javaexercises: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/java/com/dataartisans/flinktraining/exercises/datastream_java
scalaexercises: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/scala/com/dataartisans/flinktraining/exercises/datastream_scala
javaexamples: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/java/com/dataartisans/flinktraining/examples
scalaexamples: https://github.com/dataArtisans/flink-training-exercises/blob/master/src/main/scala/com/dataartisans/flinktraining/examples

scala_version: "2.11"

# Build settings
markdown: kramdown

# Used in some documents to initialize arrays. Don't delete.
array: []
